# Generated by Django 2.1.1 on 2018-09-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('Component', models.CharField(max_length=255)),
                ('Version', models.CharField(max_length=255)),
                ('Responsible', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
