name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag raphaelfabricios/backend:$(date +%s) --tag raphaelfabricios/backend:latest
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v1
    - name: Docker push
      run: docker push raphaelfabricios/backend:latest
